apiVersion: apps/v1
kind: Deployment
metadata: 
    name: busybox-deployment
    labels:
        app: frontend1
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend1
    template:
        metadata:
            labels:
                app: frontend1
        spec:
           containers:
               - name: frontend1
                 image: busybox
                 args:
                   - "/bin/sh"
                   - "-c"
                   - "touch /tmp/healthy; sleep 3600"
