apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: dockerjain/springiodemo1
        ports:
        - containerPort: 8090
