apiVersion: batch/v1
kind: Job
metadata:
  name: piii
spec:
  completions: 5
  parallelism: 3
  template:
    spec:
      containers:
      - name: piii
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4


