{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "kube-prometheus-alertmanager-lb",
    "namespace": "monitoring",
    "selfLink": "/api/v1/namespaces/monitoring/services/kube-prometheus-alertmanager",
    "labels": {
      "alertmanager": "kube-prometheus",
      "app": "alertmanager",
      "chart": "alertmanager-0.1.2",
      "heritage": "Tiller",
      "release": "kube-prometheus"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 9093,
        "targetPort": 9093
      }
    ],
    "selector": {
      "alertmanager": "kube-prometheus",
      "app": "alertmanager"
    },
    "type": "LoadBalancer",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}
