apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webservicesecret
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webservicesecret
    spec:
      containers:
      - name: webservicesecret
        image: dockerjain/restful-web-services:v2
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: webservicevol
          mountPath: /opt/ashish
      volumes:
      - name: webservicevol
        secret:
          secretName: db-user-pass
