apiVersion: v1
kind: Service
metadata:
  labels:
    app: webservicesecret
  name: webservice-svc-secret
  namespace: default
spec:
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888
  selector:
    app: webservicesecret
  type: LoadBalancer

