apiVersion: v1
kind: Service
metadata:
  labels:
    app: webservice
  name: webservice-svc
  namespace: default
spec:
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888
  selector:
    app: webservice
  type: LoadBalancer

